# Generated by Django 3.2.4 on 2021-06-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0002_auto_20210607_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ctg',
            field=models.CharField(max_length=2000),
        ),
    ]
