# Generated by Django 3.2.4 on 2021-06-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0003_alter_student_ctg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fl',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='student',
            name='geog',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='student',
            name='hist',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='student',
            name='lsc',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='student',
            name='math',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='student',
            name='psc',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='student',
            name='sl',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='student',
            name='sub1',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='student',
            name='sub2',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='student',
            name='sub3',
            field=models.CharField(max_length=2000),
        ),
    ]
