# Generated by Django 3.2.4 on 2021-06-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0005_auto_20210607_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
