# Generated by Django 3.2.4 on 2021-06-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0006_student_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fl',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='student',
            name='geog',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='student',
            name='hist',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='student',
            name='lsc',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='student',
            name='math',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='student',
            name='psc',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='student',
            name='sl',
            field=models.CharField(max_length=2000),
        ),
    ]
