# Generated by Django 3.2.4 on 2021-06-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0007_auto_20210608_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ctg',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='fl',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='fname',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='student',
            name='geog',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='hist',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='lsc',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='math',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='student',
            name='psc',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='regno',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='student',
            name='rollno',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='student',
            name='sl',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='sub1',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='sub2',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='sub3',
            field=models.CharField(max_length=2),
        ),
    ]
