# Generated by Django 3.2.4 on 2021-06-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0010_alter_student_fl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='geog',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='hist',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='lsc',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='math',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='psc',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='sl',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
