# Generated by Django 3.2.4 on 2021-06-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0012_auto_20210612_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subj',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
