# Generated by Django 3.2.3 on 2021-06-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0013_student_subj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='student',
            name='sub3',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='subj',
            field=models.CharField(max_length=40),
        ),
    ]
