# Generated by Django 3.2.3 on 2021-06-17 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0014_auto_20210617_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='sub3',
        ),
    ]
