# Generated by Django 3.2.3 on 2021-06-17 15:26

from django.db import migrations, models
import marks.validators


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0015_remove_student_sub3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fl',
            field=models.CharField(blank=True, max_length=3, null=True, validators=[marks.validators.validate_marks]),
        ),
        migrations.AlterField(
            model_name='student',
            name='geog',
            field=models.CharField(blank=True, max_length=3, null=True, validators=[marks.validators.validate_marks]),
        ),
        migrations.AlterField(
            model_name='student',
            name='hist',
            field=models.CharField(blank=True, max_length=3, null=True, validators=[marks.validators.validate_marks]),
        ),
        migrations.AlterField(
            model_name='student',
            name='lsc',
            field=models.CharField(blank=True, max_length=3, null=True, validators=[marks.validators.validate_marks]),
        ),
        migrations.AlterField(
            model_name='student',
            name='math',
            field=models.CharField(blank=True, max_length=3, null=True, validators=[marks.validators.validate_marks]),
        ),
        migrations.AlterField(
            model_name='student',
            name='psc',
            field=models.CharField(blank=True, max_length=3, null=True, validators=[marks.validators.validate_marks]),
        ),
        migrations.AlterField(
            model_name='student',
            name='sl',
            field=models.CharField(blank=True, max_length=3, null=True, validators=[marks.validators.validate_marks]),
        ),
    ]
