# Generated by Django 3.2.3 on 2021-06-17 17:54

from django.db import migrations, models
import marks.validators


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0016_auto_20210617_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.CharField(max_length=8, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='student',
            name='fname',
            field=models.CharField(max_length=40, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='geog',
            field=models.CharField(blank=True, max_length=3, null=True, validators=[marks.validators.validate_marks], verbose_name='Geography'),
        ),
        migrations.AlterField(
            model_name='student',
            name='hist',
            field=models.CharField(blank=True, max_length=3, null=True, validators=[marks.validators.validate_marks], verbose_name='History'),
        ),
        migrations.AlterField(
            model_name='student',
            name='lsc',
            field=models.CharField(blank=True, max_length=3, null=True, validators=[marks.validators.validate_marks], verbose_name='Life Science'),
        ),
        migrations.AlterField(
            model_name='student',
            name='math',
            field=models.CharField(blank=True, max_length=3, null=True, validators=[marks.validators.validate_marks], verbose_name='Mathematics'),
        ),
        migrations.AlterField(
            model_name='student',
            name='psc',
            field=models.CharField(blank=True, max_length=3, null=True, validators=[marks.validators.validate_marks], verbose_name='Physical Science'),
        ),
        migrations.AlterField(
            model_name='student',
            name='regno',
            field=models.CharField(max_length=11, verbose_name='Registration Number'),
        ),
        migrations.AlterField(
            model_name='student',
            name='rollno',
            field=models.CharField(max_length=11, verbose_name='Roll-Number'),
        ),
        migrations.AlterField(
            model_name='student',
            name='subj',
            field=models.CharField(max_length=40, verbose_name='Subject Combination'),
        ),
    ]
