# Generated by Django 3.2.4 on 2021-06-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0017_auto_20210617_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.CharField(max_length=30, verbose_name='Date of Birth'),
        ),
    ]
