# Generated by Django 3.2.4 on 2021-06-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0018_alter_student_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ctg',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='sub1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='sub2',
            field=models.CharField(max_length=20),
        ),
    ]
